services:
  bronze:
    build:
      context: ./bronze
    container_name: medallion-bronze
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./data:/data

  silver:
    build:
      context: ./silver
    container_name: medallion-silver
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./data:/data
    depends_on:
      - bronze

  gold:
    build:
      context: ./gold
    container_name: medallion-gold
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./data:/data
    depends_on:
      - silver
